import type { Client } from "@/types";

export const mockClients: Client[] = [
  {
    id: "CLT001",
    clientCode: "CLT001",
    name: "Sahyadri Nagari Patsanstha",
    type: "patsanstha",
    status: "active",
    contactPerson: "Rajesh Patil",
    mobile: "9876543210",
    email: "contact@sahyadrinagari.coop",
    registrationNumber: "PNST-2018-004521",
    address: "Main Road, Shivaji Chowk",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411001",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "CLT002",
    clientCode: "CLT002",
    name: "Demo Cooperative Bank",
    type: "bank",
    status: "active",
    contactPerson: "Priya Deshmukh",
    mobile: "9876543211",
    email: "admin@democoopbank.in",
    registrationNumber: "BANK-2015-009876",
    address: "Station Road, Camp Area",
    city: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    pinCode: "422001",
    createdAt: "2023-03-20T10:00:00Z",
  },
  {
    id: "CLT003",
    clientCode: "CLT003",
    name: "Vidarbha Gramin Patsanstha",
    type: "patsanstha",
    status: "active",
    contactPerson: "Suresh Kulkarni",
    mobile: "9876543212",
    email: "info@vidarbhagramin.coop",
    registrationNumber: "PNST-2020-001234",
    address: "Gandhi Nagar",
    city: "Nagpur",
    district: "Nagpur",
    state: "Maharashtra",
    pinCode: "440001",
    createdAt: "2024-06-10T10:00:00Z",
  },
  {
    id: "CLT004",
    clientCode: "CLT004",
    name: "Konkan Urban Cooperative Bank",
    type: "bank",
    status: "pending",
    contactPerson: "Anita Joshi",
    mobile: "9876543213",
    email: "onboarding@konkanurban.coop",
    registrationNumber: "BANK-2024-000567",
    address: "Beach Road",
    city: "Ratnagiri",
    district: "Ratnagiri",
    state: "Maharashtra",
    pinCode: "415612",
    createdAt: "2025-11-01T10:00:00Z",
  },
  {
    id: "CLT005",
    clientCode: "CLT005",
    name: "Marathwada Sahakari Patsanstha",
    type: "patsanstha",
    status: "inactive",
    contactPerson: "Vikram More",
    mobile: "9876543214",
    email: "support@marathwadasahakari.coop",
    registrationNumber: "PNST-2019-007890",
    address: "Cidco Road",
    city: "Aurangabad",
    district: "Aurangabad",
    state: "Maharashtra",
    pinCode: "431001",
    createdAt: "2022-08-05T10:00:00Z",
  },
];
