import { maskAccountReference } from "@/lib/utils/mask-account-reference";
import type { Merchant } from "@/types";

type MockMerchantInput = Omit<Merchant, "merchantCode" | "maskedCurrentAccountReference"> & {
  currentAccountReference: string;
};

function mockMerchant(data: MockMerchantInput): Merchant {
  return {
    ...data,
    merchantCode: data.id,
    maskedCurrentAccountReference: maskAccountReference(
      data.currentAccountReference
    ),
  };
}

export const mockMerchants: Merchant[] = [
  mockMerchant({
    id: "MCH001",
    clientId: "CLT001",
    businessName: "Sai Traders",
    accountHolderName: "Ramesh Jadhav",
    currentAccountReference: "CA-SN-2024-0001",
    merchantCategory: "Retail",
    businessType: "Proprietorship",
    gstNumber: "27AABCS1234F1Z5",
    pan: "AABCS1234F",
    mobile: "9123456780",
    email: "sai.traders@example.com",
    address: "Shop No. 12, Laxmi Market",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411002",
    status: "active",
    createdAt: "2023-04-10T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH002",
    clientId: "CLT001",
    businessName: "Om Medical",
    accountHolderName: "Dr. Sunil Pawar",
    currentAccountReference: "CA-SN-2024-0002",
    merchantCategory: "Healthcare",
    businessType: "Proprietorship",
    mobile: "9123456781",
    email: "om.medical@example.com",
    address: "Near Civil Hospital",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411003",
    status: "active",
    createdAt: "2023-05-15T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH003",
    clientId: "CLT001",
    businessName: "Shree Electronics",
    accountHolderName: "Amit Shinde",
    currentAccountReference: "CA-SN-2024-0003",
    merchantCategory: "Electronics",
    businessType: "Partnership",
    gstNumber: "27AABCE5678G1Z2",
    mobile: "9123456782",
    email: "shree.electronics@example.com",
    address: "FC Road",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    pinCode: "411004",
    status: "active",
    createdAt: "2023-06-20T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH004",
    clientId: "CLT002",
    businessName: "Ganesh Hardware",
    accountHolderName: "Ganesh Patil",
    currentAccountReference: "CA-DCB-2024-0001",
    merchantCategory: "Hardware",
    businessType: "Proprietorship",
    mobile: "9123456783",
    email: "ganesh.hardware@example.com",
    address: "M.G. Road",
    city: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    pinCode: "422002",
    status: "active",
    createdAt: "2023-07-01T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH005",
    clientId: "CLT002",
    businessName: "Krishna Enterprises",
    accountHolderName: "Krishna Desai",
    currentAccountReference: "CA-DCB-2024-0002",
    merchantCategory: "Wholesale",
    businessType: "Private Limited",
    gstNumber: "27AABCK9012H1Z8",
    pan: "AABCK9012H",
    mobile: "9123456784",
    email: "krishna.enterprises@example.com",
    address: "Ambad Industrial Area",
    city: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    pinCode: "422010",
    status: "active",
    createdAt: "2023-08-12T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH006",
    clientId: "CLT003",
    businessName: "Maharashtra Kirana",
    accountHolderName: "Vijay Bhosale",
    currentAccountReference: "CA-VG-2024-0001",
    merchantCategory: "Grocery",
    businessType: "Proprietorship",
    mobile: "9123456785",
    email: "mh.kirana@example.com",
    address: "Sitabuldi",
    city: "Nagpur",
    district: "Nagpur",
    state: "Maharashtra",
    pinCode: "440012",
    status: "active",
    createdAt: "2024-07-01T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH007",
    clientId: "CLT003",
    businessName: "Orange City Restaurant",
    accountHolderName: "Sanjay Verma",
    currentAccountReference: "CA-VG-2024-0002",
    merchantCategory: "Food & Beverage",
    businessType: "Partnership",
    gstNumber: "27AABCO3456I1Z3",
    mobile: "9123456786",
    email: "orange.city@example.com",
    address: "Dharampeth",
    city: "Nagpur",
    district: "Nagpur",
    state: "Maharashtra",
    pinCode: "440010",
    status: "active",
    createdAt: "2024-08-15T10:00:00Z",
  }),
  mockMerchant({
    id: "MCH008",
    clientId: "CLT005",
    businessName: "Aurangabad Textiles",
    accountHolderName: "Farooq Sheikh",
    currentAccountReference: "CA-MS-2023-0001",
    merchantCategory: "Textiles",
    businessType: "Proprietorship",
    mobile: "9123456787",
    email: "aurangabad.textiles@example.com",
    address: "Paithan Gate",
    city: "Aurangabad",
    district: "Aurangabad",
    state: "Maharashtra",
    pinCode: "431005",
    status: "inactive",
    createdAt: "2022-09-01T10:00:00Z",
  }),
];
