import type { QRCode } from "@/types";

function legacyQr(
  data: Omit<QRCode, "provider" | "providerMode" | "isPayable"> &
    Partial<Pick<QRCode, "provider" | "providerMode" | "isPayable">>
): QRCode {
  return {
    provider: "sabpaisa",
    providerMode: "legacy",
    isPayable: false,
    ...data,
  };
}

export const mockQRCodes: QRCode[] = [
  // Sai Traders (MCH001, CLT001)
  legacyQr({
    id: "QR001",
    clientId: "CLT001",
    merchantId: "MCH001",
    sabpaisaQrId: "SP-DEMO-001",
    qrName: "Sai Traders Counter 1",
    qrIdentifier: "SAI-TRD-001",
    railId: "HDFC",
    vpa: "saitraders@mahacred",
    qrImageUrl: "/demo-qr.svg",
    maxAmountPerTransaction: 50000,
    description: "Main counter QR",
    category: "Retail",
    status: "active",
    createdAt: "2023-04-15T10:00:00Z",
  }),
  legacyQr({
    id: "QR002",
    clientId: "CLT001",
    merchantId: "MCH001",
    sabpaisaQrId: "SP-DEMO-002",
    qrName: "Sai Traders Counter 2",
    qrIdentifier: "SAI-TRD-002",
    railId: "ICICI",
    vpa: "saitraders2@mahacred",
    qrImageUrl: "/demo-qr.svg",
    description: "Secondary counter",
    category: "Retail",
    status: "active",
    createdAt: "2023-05-01T10:00:00Z",
  }),
  // Om Medical (MCH002, CLT001)
  legacyQr({
    id: "QR003",
    clientId: "CLT001",
    merchantId: "MCH002",
    sabpaisaQrId: "SP-DEMO-003",
    qrName: "Om Medical Reception",
    qrIdentifier: "OM-MED-001",
    railId: "HDFC",
    vpa: "ommedical@mahacred",
    qrImageUrl: "/demo-qr.svg",
    maxAmountPerTransaction: 25000,
    description: "Reception payment QR",
    category: "Healthcare",
    status: "active",
    createdAt: "2023-05-20T10:00:00Z",
  }),
  // Shree Electronics (MCH003, CLT001)
  legacyQr({
    id: "QR004",
    clientId: "CLT001",
    merchantId: "MCH003",
    sabpaisaQrId: "SP-DEMO-004",
    qrName: "Shree Electronics Store",
    qrIdentifier: "SHR-ELC-001",
    railId: "ICICI",
    vpa: "shreeelectronics@mahacred",
    qrImageUrl: "/demo-qr.svg",
    maxAmountPerTransaction: 100000,
    description: "Store front QR",
    category: "Electronics",
    status: "active",
    createdAt: "2023-06-25T10:00:00Z",
  }),
  // Ganesh Hardware (MCH004, CLT002)
  legacyQr({
    id: "QR005",
    clientId: "CLT002",
    merchantId: "MCH004",
    sabpaisaQrId: "SP-DEMO-005",
    qrName: "Ganesh Hardware Main",
    qrIdentifier: "GAN-HRD-001",
    railId: "HDFC",
    vpa: "ganeshhardware@mahacred",
    qrImageUrl: "/demo-qr.svg",
    description: "Main shop QR",
    category: "Hardware",
    status: "active",
    createdAt: "2023-07-05T10:00:00Z",
  }),
  // Krishna Enterprises (MCH005, CLT002)
  legacyQr({
    id: "QR006",
    clientId: "CLT002",
    merchantId: "MCH005",
    sabpaisaQrId: "SP-DEMO-006",
    qrName: "Krishna Enterprises Billing",
    qrIdentifier: "KRI-ENT-001",
    railId: "ICICI",
    vpa: "krishnaent@mahacred",
    qrImageUrl: "/demo-qr.svg",
    maxAmountPerTransaction: 200000,
    description: "Billing desk QR",
    category: "Wholesale",
    status: "active",
    createdAt: "2023-08-15T10:00:00Z",
  }),
  legacyQr({
    id: "QR007",
    clientId: "CLT002",
    merchantId: "MCH005",
    sabpaisaQrId: "SP-DEMO-007",
    qrName: "Krishna Enterprises Warehouse",
    qrIdentifier: "KRI-ENT-002",
    railId: "HDFC",
    vpa: "krishnaent2@mahacred",
    qrImageUrl: "/demo-qr.svg",
    description: "Warehouse QR",
    category: "Wholesale",
    status: "inactive",
    createdAt: "2023-09-01T10:00:00Z",
  }),
  // Maharashtra Kirana (MCH006, CLT003)
  legacyQr({
    id: "QR008",
    clientId: "CLT003",
    merchantId: "MCH006",
    sabpaisaQrId: "SP-DEMO-008",
    qrName: "Maharashtra Kirana Shop",
    qrIdentifier: "MH-KIR-001",
    railId: "HDFC",
    vpa: "mhkirana@mahacred",
    qrImageUrl: "/demo-qr.svg",
    description: "Shop counter QR",
    category: "Grocery",
    status: "active",
    createdAt: "2024-07-05T10:00:00Z",
  }),
  // Orange City Restaurant (MCH007, CLT003)
  legacyQr({
    id: "QR009",
    clientId: "CLT003",
    merchantId: "MCH007",
    sabpaisaQrId: "SP-DEMO-009",
    qrName: "Orange City Dining",
    qrIdentifier: "ORG-RES-001",
    railId: "ICICI",
    vpa: "orangecity@mahacred",
    qrImageUrl: "/demo-qr.svg",
    maxAmountPerTransaction: 15000,
    description: "Table payment QR",
    category: "Food & Beverage",
    status: "active",
    createdAt: "2024-08-20T10:00:00Z",
  }),
  // Aurangabad Textiles (MCH008, CLT005)
  legacyQr({
    id: "QR010",
    clientId: "CLT005",
    merchantId: "MCH008",
    sabpaisaQrId: "SP-DEMO-010",
    qrName: "Aurangabad Textiles Shop",
    qrIdentifier: "AUR-TEX-001",
    railId: "HDFC",
    vpa: "aurangabadtextiles@mahacred",
    qrImageUrl: "/demo-qr.svg",
    description: "Shop QR",
    category: "Textiles",
    status: "inactive",
    createdAt: "2022-09-10T10:00:00Z",
  }),
];
